# -*- coding: utf-8 -*-
"""Generate Module 3 Word quiz explanations JSONL."""
import json
from pathlib import Path

OUT = Path(r"C:\Users\thuanht\Downloads\Thi THVP\quiz\_new_m3.jsonl")
SRC = Path(r"C:\Users\thuanht\Downloads\Thi THVP\quiz\_src_m3.json")

# (id, icon, explain, detail)
RECORDS = [
(1, "🚀",
 "Cách phổ biến nhất là kích đúp biểu tượng lối tắt (shortcut) Microsoft Office Word trên Desktop hoặc thanh tác vụ.",
 "Shortcut chỉ trỏ tới chương trình Word đã cài; không phải file văn bản. Phương án A nhầm sang PowerPoint; B và D không phải đường khởi động chuẩn trên Windows hiện nay."),
(2, "📐",
 "Ctrl + E căn đoạn đang chọn vào giữa trang (Center), thường dùng cho tiêu đề.",
 "Trong Word: Ctrl + L căn trái, Ctrl + R căn phải, Ctrl + J căn đều hai bên (Justify), Ctrl + E căn giữa. Nhầm dễ gặp: tưởng E là “lề trái” vì chữ Left cũng bắt đầu bằng L, nhưng Center mới gắn với E."),
(3, "📄",
 "Từ Word 2007/2010 trở đi, định dạng lưu mặc định là .docx (Office Open XML).",
 ".doc là định dạng Word cũ (97–2003); .xlsx là Excel; .pdf là Portable Document Format dùng để chia sẻ/in. Muốn lưu .doc hoặc .pdf thì dùng File → Save As và chọn kiểu file."),
(4, "🔗",
 "Ctrl + K mở hộp thoại Hyperlink để gắn liên kết tới web, file hoặc vị trí trong tài liệu.",
 "Không nhầm với Ctrl + F (tìm kiếm) hay Ctrl + D (hộp thoại Font). Ví dụ: bôi tên “Trang chủ”, Ctrl + K, dán URL — chữ trở thành liên kết có thể bấm."),
(5, "✏️",
 "Word, LibreOffice Writer và OpenOffice Writer đều là phần mềm soạn thảo văn bản, nên chọn cả ba.",
 "Cùng nhóm word processor: tạo, sửa, định dạng và in văn bản. Khi đề có “cả (1)+(2)+(3)”, hãy kiểm tra từng ý — nếu cả ba đều đúng thì không chọn một phần mềm đơn lẻ."),
(6, "📝",
 "Soạn thảo văn bản gồm đủ: xem nội dung, sửa/bổ sung bất kỳ chỗ nào, lưu và in — nên chọn cả ba chức năng.",
 "Đó là đặc trưng của word processor so với chỉ xem PDF tĩnh. Không chọn riêng (1), (2) hay (3) vì đề hỏi chức năng chính ở mức tổng quát."),
(7, "🚪",
 "File → Close đóng tài liệu đang làm việc (cửa sổ văn bản), không thoát hẳn Word nếu còn file khác.",
 "File → Save chỉ lưu; File → Open mở file khác; File → Print in. Muốn thoát cả chương trình dùng File → Exit hoặc nút đóng cửa sổ ứng dụng."),
(8, "💾",
 "File → Save (hoặc Ctrl + S) ghi nội dung hiện tại xuống ổ đĩa theo tên và thư mục đã có.",
 "Save As dùng khi muốn đổi tên/đường dẫn hoặc kiểu file; Close đóng file; không có lệnh “Save as wizard” chuẩn. Lưu thường xuyên để tránh mất bài khi treo máy."),
(9, "🆕",
 "Ctrl + N tạo tài liệu Word mới (blank document) ngay lập tức.",
 "Mẹo nhớ: N = New. Ctrl + O = Open, Ctrl + S = Save, Ctrl + W hoặc File → Close = đóng file hiện tại."),
(10, "🏷️",
 "Tên file đang mở hiện trên thanh tiêu đề (Title Bar) ở đỉnh cửa sổ Word.",
 "Thanh truy cập nhanh (Quick Access Toolbar) chứa nút Save/Undo/Redo; thanh trạng thái (Status Bar) hiện số trang, ngôn ngữ, Zoom; thước kẻ (Ruler) đo lề và tab."),
(11, "⚡",
 "Mặc định trên Quick Access Toolbar có Save, Undo và Redo — lưu, hoàn tác và làm lại.",
 "Copy không nằm sẵn trên thanh này (dùng Ctrl + C hoặc nhóm Clipboard tab Home). Có thể tùy chỉnh thêm nút bằng mũi tên cạnh thanh truy cập nhanh."),
(12, "🖨️",
 "Print Layout hiển thị trang gần như khi in: có lề, đầu trang, chân trang và ngắt trang rõ.",
 "Web Layout xem kiểu trang web; Full Screen Reading ưu tiên đọc; Zoom phóng to/thu nhỏ góc nhìn chứ không đổi chế độ bố cục. Đây là chế độ mặc định khi soạn văn bản hành chính."),
(13, "📖",
 "Full Screen Reading (Reading View) phóng to vùng đọc và hạn chế sửa nội dung, phù hợp đọc tài liệu.",
 "Print Layout và Web Layout vẫn cho phép soạn thảo bình thường. Trong Word 2010 tên là Full Screen Reading; bản mới hơn gọi Reading Mode."),
(14, "❓",
 "Help trong Word giúp tra cứu cách dùng lệnh và chức năng ngay trong ứng dụng.",
 "Không phải công cụ tìm-thay thế văn bản (Ctrl + H) hay tìm chuỗi trong tài liệu (Ctrl + F). Bấm F1 hoặc nút ? để mở."),
(15, "⌨️",
 "Phím F1 mở trợ giúp (Help) của Microsoft Word.",
 "F2 thường đổi tên/sửa; F4 lặp lại thao tác; F3 có thể chèn AutoText tùy cấu hình — không mở Help. Ghi nhớ: F1 = Help gần như mọi phần mềm Windows."),
(16, "💻",
 "Chỉ cần máy đã cài Word (đề nêu Word 2010) là dùng được Help tích hợp trong phần mềm.",
 "Unikey/Vietkey chỉ hỗ trợ gõ tiếng Việt, không liên quan Help. Kết nối mạng hữu ích cho nội dung online nhưng không phải điều kiện bắt buộc theo đáp án đề."),
(17, "🌐",
 "Web Layout hiển thị văn bản theo kiểu trang web: chảy liên tục, không nhấn mạnh khổ giấy in.",
 "Print Layout mô phỏng trang in; Full Screen Reading để đọc. Chọn Web Layout khi soạn nội dung sẽ xuất HTML hoặc xem trước trên web."),
(18, "🔍",
 "Zoom 100% nghĩa là kích thước hiển thị khớp kích thước thực khi in ra giấy (actual size).",
 "Không phải phóng gấp đôi (đó là ~200%), cũng không đồng nghĩa chuyển sang Full Screen Reading hay Web Layout. Thanh Zoom chỉ đổi góc nhìn, không đổi nội dung file."),
(19, "🪟",
 "Tab View chứa nhóm Window với các lệnh sắp xếp và chuyển cửa sổ văn bản.",
 "File quản lý mở/lưu/in; Home định dạng chữ/đoạn; Page Layout (Layout) chỉnh khổ giấy, lề, hướng. Muốn Arrange All hay Switch Windows thì vào View."),
(20, "🖥️",
 "Full Screen Reading dùng gần hết màn hình để đọc, vùng hiển thị lớn nhất trong các chế độ View thông dụng.",
 "Draft và Outline phục vụ soạn/ cấu trúc đề mục, không tối ưu “phóng to toàn màn”. Web Layout vẫn giữ giao diện soạn thảo bình thường."),
(21, "🔄",
 "View → Switch Windows liệt kê và chuyển nhanh giữa các file Word đang mở.",
 "Arrange All xếp nhiều cửa sổ cùng lúc; Split tách một cửa sổ thành hai khung; Show bật Ruler/Gridlines… Không dùng để nhảy sang file khác."),
(22, "⬜",
 "Nút Maximize nằm góc trên bên phải cửa sổ (cạnh Minimize và Close), phóng to cửa sổ Word hết màn hình làm việc.",
 "Bên trái là biểu tượng ứng dụng/menu hệ thống; không có Maximize dưới hay trái. Sau khi Maximize, nút đổi thành Restore Down."),
(23, "⏱️",
 "Save AutoRecover information every đặt khoảng phút Word tự lưu bản phục hồi (AutoRecover).",
 "Không phải đổi tên file (Save As) hay tự đóng/mở file. Khi Word treo hoặc mất điện, có thể khôi phục từ bản AutoRecover lần gần nhất."),
(24, "📁",
 "Đổi thư mục lưu mặc định tại File → Options → Save → Default file location.",
 "AutoRecover file location là chỗ chứa bản phục hồi tạm, khác thư mục Save mặc định. Không tìm Default file location ngay trong hộp thoại Save thường ngày."),
(25, "📏",
 "Bật đường biên vùng chữ (Show Text Boundaries) ở File → Options → Advanced.",
 "Options luôn nằm dưới menu File, không phải View/Home/Insert. Đường biên giúp thấy vùng soạn trong lề khi chỉnh bố cục."),
(26, "📂",
 "Ctrl + O mở hộp thoại Open để chọn và mở file Word (hoặc định dạng tương thích) đã có trên máy.",
 "O = Open. Không tạo file mới (Ctrl + N), không lưu (Ctrl + S), không đóng file."),
(27, "⌨️",
 "Ctrl + O là phím tắt chuẩn để mở văn bản có sẵn.",
 "Shift + O hay Alt + O không mở hộp thoại Open trong Word. Cũng có thể File → Open hoặc biểu tượng Open trên Quick Access nếu đã ghim."),
(28, "📊",
 "Phải Copy dữ liệu Excel trước, rồi Home → Paste → Paste Special → chọn Microsoft Excel Worksheet Object → OK.",
 "Thiếu bước Copy thì Paste Special không có đối tượng Excel. Paste Special dạng Object giúp nhúng/liên kết bảng tính thay vì chỉ dán giá trị tĩnh."),
(29, "©️",
 "Ký hiệu © (copyright) thuộc nhóm ký tự/ký hiệu đặc biệt, không phải chữ cái thường trên bàn phím.",
 "Chèn bằng Insert → Symbol hoặc Alt-code. Phân biệt với chữ viết thông thường và với hình ảnh (Picture)."),
(30, "🔣",
 "Dấu ≥ không có phím riêng trên bàn phím chuẩn; chèn qua Insert → Symbol (More Symbols).",
 "Gõ > rồi = chỉ ra hai ký tự riêng, không thành ≥. Spelling and Grammar không chèn ký hiệu toán."),
(31, "®️",
 "® nằm trong tab Special Characters của More Symbols: Insert → Symbol → More Symbols → Special Characters.",
 "Webdings/Wingdings là font biểu tượng trang trí, không phải chỗ chuẩn để lấy ®. Chọn ® rồi Insert."),
(32, "💾",
 "Ctrl + S lưu (Save) thay đổi vào file hiện tại.",
 "S = Save. Ctrl + N tạo mới; Ctrl + O mở; đóng file dùng Ctrl + W hoặc File → Close. Nên lưu trước khi nghỉ hoặc in."),
(33, "📛",
 "File → Save As lưu bản sao với tên, thư mục hoặc kiểu file mới; file gốc giữ nguyên nếu đổi tên.",
 "Save chỉ ghi đè bản hiện tại. Lệnh Save/Save As nằm menu File, không phải tab Home."),
(34, "📑",
 "Word có thể lưu .doc, .docx và .pdf (qua Save As / Save as type).",
 ".xlsx/.xls là Excel — không phải định dạng văn bản Word. Thực tế: File → Save As → chọn Word Document, Word 97-2003, hoặc PDF."),
(35, "🪟",
 "View → Window → Arrange All xếp tất cả cửa sổ Word đang mở lên màn hình để xem song song.",
 "Không có nhóm Window trên Home/Review/File. Dùng khi cần đối chiếu hai bản thảo cùng lúc."),
(36, "📐",
 "Vào tab View, nhóm Window, chọn kiểu sắp xếp (Arrange All, View Side by Side…).",
 "Insert/Home/Review không quản lý cửa sổ. Switch Windows chuyển file; Arrange All hiện nhiều cửa sổ cùng lúc."),
(37, "🗑️",
 "Bôi đen đoạn cần xóa, chuột phải, chọn Delete (hoặc bấm phím Delete/Backspace).",
 "Phải chọn văn bản trước; chuột phải không chọn gì thì không xóa đúng đoạn. Không có lệnh Remove chuẩn như vậy trong Word."),
(38, "👆",
 "Ba lần click chuột trái ở vùng lề trái (selection bar) chọn toàn bộ văn bản.",
 "Cách khác nhanh: Ctrl + A. Click phải không dùng để bôi chọn kiểu này; lề phải/dưới không phải vùng chọn chuẩn."),
(39, "📄",
 "Ctrl + G mở Go To; trong Enter page number gõ số trang rồi Enter để nhảy tới trang đó.",
 "Ctrl + F tìm chữ; Ctrl + H tìm và thay; Ctrl + D mở Font. Mẹo: G = Go To."),
(40, "💯",
 "Giữ Shift rồi bấm phím số 5 để gõ ký tự % (hàng số phía trên bàn phím).",
 "Chỉ bấm 5 ra số 5; Alt/Ctrl + 5 không tạo % trên layout chuẩn. Shift + số là cách lấy ký hiệu hàng trên."),
(41, "✂️",
 "Bôi khối văn bản rồi bấm Delete để xóa khối đó.",
 "Tab chỉ thụt/ nhảy ô; Ctrl + Delete xóa từ bên phải con trỏ, không phải cách chuẩn xóa cả khối đã chọn. Đã chọn sẵn thì Delete là đủ."),
(42, "🔣",
 "Chèn ký tự đặc biệt bằng Insert → Symbol.",
 "Không có Symbol trên Format/View/Tools theo ribbon Word hiện đại. Sau đó chọn font/symbol hoặc Special Characters."),
(43, "🔀",
 "Ctrl + H mở Find and Replace để tìm và thay thế hàng loạt trong tài liệu.",
 "H gắn với Replace (trong nhiều bản Word). Ctrl + F chủ yếu để Find; Ctrl + D là Font. Ví dụ thay “UBND” thành “Ủy ban nhân dân” một lần."),
(44, "🔎",
 "Ctrl + F mở tìm kiếm (Find) để định vị chuỗi trong văn bản.",
 "Không mở Help (F1), không phải hộp Replace đầy đủ như Ctrl + H, cũng không phải AutoCorrect. Navigation Pane hiện các kết quả khớp."),
(45, "📝",
 "Ô Find what là nơi nhập từ/cụm từ cần tìm.",
 "Từ thay thế nằm ở Replace with (tab Replace). Match case / Find whole words là tùy chọn nâng cao, không phải ô Find what."),
(46, "🔠",
 "Ctrl + A chọn (Select All) toàn bộ nội dung tài liệu đang mở.",
 "A = All. Ctrl + F là tìm; Alt + A/F không chọn hết văn bản. Dùng trước khi đổi font toàn bài hoặc copy cả tài liệu."),
(47, "📋",
 "Cắt bằng Ctrl + X, sang file đích dán bằng Ctrl + V — đoạn biến mất ở file nguồn và xuất hiện ở đích.",
 "Ctrl + C là Copy (nhân bản, nguồn còn nguyên). Cắt dùng khi muốn di chuyển, không nhân đôi nội dung."),
(48, "↩️",
 "Ctrl + Z hoàn tác (Undo) — đưa văn bản về trạng thái trước thao tác vừa làm.",
 "Khác đóng cửa sổ/file. Redo (Ctrl + Y) làm lại sau khi Undo. Mẹo: Z gần phím Ctrl, thao tác “lùi một bước” rất thường dùng."),
(49, "⏪",
 "Undo (Ctrl + Z hoặc nút trên Quick Access) khôi phục trạng thái trước thao tác gần nhất.",
 "Redo làm lại việc đã Undo; Open mở file; Quick Print in nhanh — không phục hồi nội dung vừa sửa nhầm."),
(50, "🛠️",
 "Tắt/xóa mục AutoCorrect tại File → Options → Proofing → AutoCorrect Options → Delete mục gây sai tiếng Việt.",
 "AutoCorrect nằm trong Options/Proofing, không phải tab Home. Ví dụ xóa cặp tự sửa biến “đươc” thành chuỗi không mong muốn."),
(51, "🔴",
 "Gạch chân đỏ/xanh là cảnh báo chính tả/ngữ pháp; tắt bằng File → Options → Proofing, bỏ chọn các mục When correcting spelling and grammar in Word.",
 "Với tiếng Việt, Word thường không có từ điển tốt nên gạch đỏ nhiều — tắt kiểm tra giúp giao diện sạch khi soạn công văn."),
(52, "🔤",
 "Ctrl + ] tăng cỡ chữ vùng chọn từng bước một.",
 "Ctrl + [ giảm cỡ chữ; Ctrl + B là in đậm. Có thể dùng luôn nút Increase Font Size trên tab Home → Font."),
(53, "🅱️",
 "Ctrl + B bật/tắt chữ đậm (Bold) cho văn bản đang chọn.",
 "B = Bold. Nghiêng là Ctrl + I (Italic); gạch chân Ctrl + U. Đáp án nhấn mạnh chuyển chữ thường sang đậm — đúng hành vi toggle Bold."),
(54, "⬇️",
 "Chỉ số dưới (Subscript) làm được bằng nút Subscript trên ribbon, Ctrl + =, hoặc Ctrl + D → chọn Subscript — cả ba cách đều đúng.",
 "Dùng cho H₂O, công thức hóa. Chỉ số trên (Superscript) thường là Ctrl + Shift + = — khác phím chỉ số dưới."),
(55, "⬆️",
 "Đang ở chỉ số trên thì tắt bằng nút Superscript trên ribbon, Ctrl + Shift + =, hoặc hộp thoại Font (Ctrl + D) — các cách đề liệt kê đều được chấp nhận.",
 "Superscript/Subscript là nút bật-tắt: bấm lại cùng lệnh sẽ về dòng chữ thường. Tránh để vừa trên vừa dưới cùng lúc."),
(56, "🎨",
 "Đổ màu nền đoạn/ô bằng Home → Paragraph → Shading (tô nền đoạn).",
 "Text Highlight Color trong nhóm Font là bút dạ quang từng chữ, khác Shading. Không tìm Shading trên tab Insert."),
(57, "🔠",
 "Khi đèn Caps Lock sáng, mọi chữ cái gõ ra đều IN HOA.",
 "Không tự thêm dấu chấm hay in đậm đầu dòng. Muốn hoa tạm thời từng ký tự thì giữ Shift; muốn đổi đoạn đã gõ dùng Change Case."),
(58, "⌨️",
 "Bấm Caps Lock thêm một lần nữa để tắt — đây là phím gạt (toggle).",
 "Không tự tắt sau vài giây; ESC không tắt Caps Lock. Quan sát đèn bàn phím hoặc biểu tượng trên màn hình để biết đang bật/tắt."),
(59, "🔠",
 "Bật Caps Lock rồi gõ chữ cái sẽ ra chữ in hoa.",
 "Giống câu về Caps Lock sáng: trạng thái hoa áp dụng cho phím chữ. Kết hợp Shift khi Caps Lock đang bật sẽ ra chữ thường."),
(60, "🔤",
 "Upper Case (UPPERCASE) trong Change Case viết HOA toàn bộ đoạn đã chọn.",
 "Khác Sentence case (hoa đầu câu) hay Capitalize Each Word. Vào Home → Font → Change Case (biểu tượng Aa)."),
(61, "🔤",
 "Lower Case đổi toàn bộ đoạn chọn thành chữ thường.",
 "Không chỉ sửa ký tự đầu. Ví dụ tiêu đề bị Caps Lock nhầm: bôi đen → Change Case → lowercase."),
(62, "🔠",
 "Đổi kiểu hoa/thường (không đổi font family) bằng Home → Font → Change Case.",
 "Increase/Decrease Font Size đổi cỡ chữ; Subscript là chỉ số dưới — không phải “kiểu chữ” hoa-thường như đề hỏi."),
(63, "➖",
 "Gạch nối từ (Hyphenation) nằm trong Page Setup: tab Page Layout (Layout) → Hyphenation.",
 "Orientation đổi dọc/ngang giấy; References là trích dẫn/mục lục — không phải chỗ tách từ cuối dòng. Bật Automatic Hyphenation khi cần đều lề với từ dài."),
(64, "👆",
 "Ba lần click chuột trái liên tiếp trên một đoạn sẽ bôi đen cả đoạn đó.",
 "Một lần đặt con trỏ; hai lần chọn từ; ba lần chọn đoạn. Click phải mở menu ngữ cảnh, không bôi đoạn theo cách này."),
(65, "↩️",
 "Phím Enter tạo dấu ngắt đoạn (paragraph break) — bắt đầu đoạn mới.",
 "Shift + Enter chỉ xuống dòng mềm (line break) trong cùng đoạn; Ctrl + Enter ngắt trang (Page Break). Chọn đúng Enter khi đề hỏi ngắt đoạn."),
(66, "⬅️",
 "Thụt cả đoạn về trái theo số đo: hộp thoại Paragraph → Indentation → Left.",
 "Spacing Before/After là khoảng cách trên/dưới đoạn, không phải thụt lề. Mở nhanh: Home → Paragraph → nút góc dưới nhóm."),
(67, "➡️",
 "Thụt đoạn về phải: Paragraph → Indentation → Right.",
 "Indentation Left là thụt trái; Spacing không chỉnh thụt. Ví dụ trích dẫn dài thường tăng Left và Right cùng lúc."),
(68, "📏",
 "Word hỗ trợ First line (thụt dòng đầu), Hanging (treo đầu dòng) và thụt Left — cả ba kiểu đều đúng.",
 "First line dùng mở đoạn văn; Hanging phổ biến trong danh mục tài liệu tham khảo. Đặt trong Paragraph → Special hoặc kéo marker trên Ruler."),
(69, "📐",
 "Bật/tắt thước kẻ: View → Show → đánh dấu hoặc bỏ Ruler.",
 "Không chỉnh Ruler trong File Options kiểu đó; Outline là chế độ xem đề mục. Ruler giúp kéo tab và thụt đoạn trực quan."),
(70, "⏹️",
 "Tab stop position nhập vị trí điểm dừng khi bấm phím Tab (đơn vị cm/inch trên thước).",
 "Loại Tab (Left/Center/Right/Decimal) và Leader (đường chấm) là mục khác trong cùng hộp thoại Tabs."),
(71, "🗑️",
 "Kéo thả dấu Tab trên thanh Ruler ra khỏi thước để xóa tab stop đó.",
 "Delete khi đang gõ chỉ xóa ký tự Tab trong văn bản, không xóa điểm dừng đã đặt trên Ruler. Có thể xóa trong hộp thoại Tabs → Clear."),
(72, "↕️",
 "Khoảng cách đoạn: Home → Paragraph → mở hộp thoại → Spacing → chỉnh Before và After.",
 "Clipboard là Cut/Copy/Paste — không có Spacing. Tránh tạo khoảng trống bằng nhiều lần Enter; dùng Before/After để đồng nhất."),
(73, "🔠",
 "Đổi khoảng cách ký tự: Ctrl + D → tab Advanced → Spacing chọn Expanded hoặc Condensed.",
 "Expanded giãn chữ (tiêu đề); Condensed thu hẹp. Không nhầm với Scale (kéo giãn tỷ lệ ngang) hay Number form."),
(74, "📏",
 "Line Spacing đặt tại Home → Paragraph → hộp thoại Paragraph → Spacing → Line Spacing (Single, 1.5, Double…).",
 "Nhóm Font không chứa Line Spacing; Clipboard cũng không. Văn bản hành chính thường 1.5 lines hoặc Exactly theo quy định."),
(75, "🔸",
 "Đánh dấu đầu dòng (Bullets): Home → Paragraph → Bullets.",
 "Không nằm nhóm Font hay Clipboard. Dùng cho liệt kê không cần thứ tự; cần thứ tự thì dùng Numbering."),
(76, "🔢",
 "Đánh số đề mục: Home → Paragraph → Numbering.",
 "Bullets là ký hiệu không số. Có thể chọn định dạng 1. / a. / i. trong mũi tên Numbering."),
(77, "🖼️",
 "Viền trang nghệ thuật: Home → Paragraph → Borders and Shading → tab Page Border → Style kiểu Art.",
 "Áp dụng Whole document hoặc First Page Only tùy nhu cầu. Không đi từ Insert/File để mở đủ hộp thoại này theo đáp án đề."),
(78, "⬜",
 "Viền một đoạn: Home → Paragraph → Border and Shading (hoặc nút Border).",
 "Nhóm Font không có Border đoạn; Page Layout/Design không phải đường chuẩn trong đề này. Chọn Box/Custom rồi Apply to Paragraph."),
(79, "📑",
 "Chỉ trang đầu có viền: Borders and Shading → Apply to → This section – First Page Only.",
 "Whole Document viền mọi trang; All except first page ngược lại (trang sau mới có). Hay dùng bìa có khung, thân bài không khung."),
(80, "🎨",
 "Sửa Style có sẵn: Home → Styles → chuột phải Style → Modify.",
 "Styles nằm tab Home, không phải Format/View/References. Đổi Normal/Heading một lần sẽ đồng bộ mọi đoạn đang dùng style đó."),
(81, "✨",
 "Bôi đoạn cần định dạng → Home → Styles → chọn Heading 1, Normal, Title…",
 "Không áp Style từ Review/Insert/View. Dùng Style giúp mục lục (TOC) và chỉnh sửa hàng loạt thống nhất."),
(82, "🖌️",
 "Ctrl + Shift + C copy định dạng (format) — tương tự Format Painter bằng phím tắt.",
 "Khác Ctrl + C copy nội dung. Dán định dạng thường bằng Ctrl + Shift + V. Ví dụ copy font tiêu đề sang nhiều đề mục khác."),
(83, "📊",
 "Bảng 5×6 theo cách đề nêu nghĩa là 5 cột và 6 dòng.",
 "Không phải 30 cột hay 30 dòng. Khi Insert Table, Word hỏi Number of columns và Number of rows riêng."),
(84, "📋",
 "Chèn bảng: Insert → Table → Insert Table → nhập số hàng và cột.",
 "Không có Table trên View/Home. Có thể kéo chọn lưới nhanh trong menu Table thay vì gõ số."),
(85, "🔄",
 "Đổi hướng chữ trong ô: chọn ô → Table Tools → Layout → Text Direction.",
 "Design của bảng lo viền/style/shading; Layout lo ô, hàng, hướng chữ, căn lề ô. Bấm Text Direction vài lần để xoay dọc/ngang."),
(86, "⏭️",
 "Trong bảng, phím Tab chuyển sang ô bên phải (ô kế tiếp).",
 "Ở ô cuối, Tab thường thêm một hàng mới. Shift + Tab lùi ô; Caps Lock/ESC/Ctrl không dùng để đi ô."),
(87, "🔗",
 "Gộp ô: chọn các ô → Table Tools → Layout → Merge Cells.",
 "Split Cells là tách ô — ngược lại. Merge dùng cho tiêu đề trải nhiều cột."),
(88, "↔️",
 "Đổi độ rộng ô: Table Tools → Layout → nhóm Cell Size → Width.",
 "Design không chỉnh Width ô; Home/View cũng không. Có thể kéo đường biên cột bằng chuột cho nhanh."),
(89, "🖼️",
 "Đổi kiểu viền ô: Table Tools → Design → Borders and Shading → chọn Style → OK.",
 "Viền/style bảng thuộc Design; Layout nghiêng về cấu trúc ô. Có thể dùng Border Painter trên cùng tab Design."),
(90, "🎨",
 "Tô nền ô: chọn ô → Table Tools → Design → Shading.",
 "Shading bảng nằm Design, không phải Layout. Dùng làm nổi bật hàng tiêu đề."),
(91, "🗑️",
 "Xóa cả bảng: chọn bảng → Table Tools → Layout → Delete → Delete Table.",
 "Chỉ bấm Delete khi chọn ô có thể chỉ xóa nội dung, không xóa cấu trúc bảng. Không tìm Delete Table trên Insert/Home."),
(92, "🔷",
 "Vẽ hình: Insert → Illustrations → Shapes (đường thẳng, chữ nhật, mũi tên…).",
 "Toolbar Drawing kiểu Word cũ không còn là đáp án chuẩn; Ruler chỉ là thước. Sau khi chèn, tab Format xuất hiện để chỉnh shape."),
(93, "📈",
 "Chèn biểu đồ: Insert → Illustrations → Chart.",
 "Chart không nằm Review/Mailings/References. Word mở cửa sổ dữ liệu kiểu Excel để nhập số liệu biểu đồ."),
(94, "🖼️",
 "Nhóm đối tượng đồ họa (Picture, Shapes, Chart…) nằm Insert → Illustrations.",
 "Home không có Illustrations; Design của bảng/theme khác nhóm chèn hình. Picture đôi khi tách nút riêng nhưng vẫn thuộc khu vực Insert."),
(95, "🖼️",
 "Insert → Illustrations → Picture chèn ảnh từ file trên máy vào tài liệu.",
 "Không phải chèn bảng (Table), biểu đồ (Chart) hay Symbol. Sau khi chèn có thể Crop, Resize trên tab Picture Format."),
(96, "✨",
 "Sau khi chèn ảnh có thể xoay, chỉnh sáng/mờ, cắt (Crop) và chèn nhiều ảnh — cả các ý đề nêu đều đúng.",
 "Công cụ nằm Picture Tools/Format. Chèn nhiều ảnh: chọn nhiều file trong hộp thoại Insert Picture."),
(97, "📦",
 "Text Box chèn từ Insert → Text Box (hoặc Shapes → Text Box).",
 "Không có Text Box trên Home/View/Review. Dùng khi cần khung chữ đặt tự do, chú thích cạnh hình."),
(98, "🖌️",
 "Đổi màu viền Text Box: tab Format (Drawing Tools) → Shape Outline → chọn màu.",
 "Shape Fill tô nền bên trong, không phải viền. Outline mới là màu đường biên."),
(99, "💾",
 "Sau khi chỉnh Text Box xong vẫn phải lưu tài liệu bằng Ctrl + S (hoặc File → Save).",
 "Text Box là một phần của file Word; không có phím Alt+S/Shift+S riêng để “lưu text box”. Ctrl + S ghi cả trang gồm text box."),
(100, "📎",
 "Chú thích cuối trang (Footnote): References → Insert Footnote.",
 "Không nằm Insert/Page Layout/Review theo đáp án chuẩn. Word đánh số và đặt nội dung chú thích cuối trang hiện tại."),
(101, "🔢",
 "Đánh số trang: Insert → Page Number (chọn vị trí đầu/cuối trang và kiểu số).",
 "Page Layout chỉnh lề/hướng; References lo footnote/mục lục. Có thể kết hợp Header & Footer."),
(102, "📐",
 "Ctrl + J căn đều hai bên (Justify): mép trái và phải thẳng hàng.",
 "Ctrl + L trái, Ctrl + R phải, Ctrl + E giữa. Thân bài công văn thường dùng Justify."),
(103, "📄",
 "Ngắt trang: Insert → Pages → Page Break (hoặc Ctrl + Enter).",
 "Đưa nội dung sau điểm ngắt sang trang mới mà không cần Enter nhiều lần. Không tìm Page Break trên View/Review."),
(104, "📑",
 "Chèn đầu trang/chân trang: Insert → nhóm Header & Footer → Header hoặc Footer.",
 "Sau khi chèn, tab Header & Footer Tools cho phép chỉnh khác trang đầu, số trang… Không dùng Format/View như Word rất cũ."),
(105, "📄",
 "Portrait là hướng giấy dọc (chiều cao lớn hơn chiều rộng).",
 "Landscape là ngang. Đổi tại Page Layout → Orientation. Công văn A4 mặc định Portrait."),
(106, "🖨️",
 "Hướng in mặc định của Word là dọc (Portrait).",
 "Chỉ đổi sang ngang khi bảng rộng hoặc slide in ngang. Kiểm tra lại Orientation trước khi in hàng loạt."),
(107, "📏",
 "Lề trang (Margins) là khoảng trống giữa cạnh giấy và vùng nội dung văn bản.",
 "Không phải khoảng “ảo” tùy ý không gắn mép giấy. Lề hẹp quá dễ bị máy in cắt chữ."),
(108, "🖼️",
 "Landscape hiển thị/in theo hướng ngang.",
 "Portrait = dọc. Ví dụ in bảng nhiều cột hoặc lịch ngang dùng Landscape."),
(109, "🔄",
 "Đổi hướng giấy: Page Layout → Page Setup → Orientation (Portrait/Landscape).",
 "Không chọn riêng nút Portrait làm “đường lệnh đổi hướng” theo đề; vào Orientation rồi chọn. Tab Design không phải chỗ Page Setup chuẩn."),
(110, "📄",
 "Định dạng trang in (khổ, lề, hướng…): File → Page Setup (hoặc hộp thoại Page Setup từ Page Layout).",
 "Print/Print Preview để in và xem trước, không phải chỗ đặt tham số trang đầy đủ như Page Setup."),
(111, "📏",
 "Theo đáp án đề: Page Layout → nhóm Paper Setup → Margins để đổi lề.",
 "Orientation đổi hướng; Size đổi khổ giấy (A4…). Thực tế ribbon thường ghi Page Setup — chọn đúng mục Margins trong các phương án."),
(112, "🖨️",
 "Xem hàng đợi in: kích đúp biểu tượng máy in trên khay hệ thống (taskbar).",
 "Cửa sổ print queue hiện tài liệu đang chờ/in. Click một lần thường chỉ hiện menu nhỏ, không đủ danh sách chi tiết."),
(113, "🚫",
 "Trong hàng đợi in: chuột phải tài liệu → Cancel để hủy lệnh in.",
 "Pause tạm dừng; Restart in lại; Properties xem thuộc tính — không hủy. Cần hủy sớm trước khi máy in kịp ra nhiều trang."),
(114, "👁️",
 "Print Preview xem trước bố cục trang như khi in, phát hiện lỗi lề/tràn chữ trước khi tốn giấy.",
 "Print Layout là chế độ soạn thảo; không có Print Test/Demo chuẩn. Trong Word 2010+ xem trước nằm trong File → Print."),
(115, "📕",
 "Lưu PDF: File → Save As (hoặc Save) → Save as type chọn PDF (*.pdf).",
 "Không lưu PDF từ Home/Insert/View. PDF giữ bố cục khi gửi người không có Word."),
(116, "🔒",
 "Đặt mật khẩu: File → Info → Protect Document → Encrypt with Password.",
 "Nhớ mật khẩu; mất có thể không mở lại được. Không có Protect Document trên Home/Insert/View."),
(117, "✉️",
 "Gửi file kèm email: File → Save & Send (hoặc Share) → Send Using E-mail.",
 "Word mở Outlook/client thư với file đính kèm. Không thực hiện từ Home/Insert/View."),
(118, "☁️",
 "Lưu lên môi trường mạng/web: File → Save & Send → Save to Web (OneDrive/SkyDrive tùy phiên bản).",
 "Cần tài khoản Microsoft/mạng. Khác Save thường chỉ lưu ổ cục bộ."),
(119, "✉️",
 "Tạo thư từ mẫu: File → New → Letters → chọn mẫu Letter → Download.",
 "Templates nằm New trong Backstage File, không phải tab Home. Wizard/mẫu giúp sẵn bố cục thư."),
(120, "🔤",
 "Theo thể thức văn bản hành chính (thông tư liên quan đề thi), font yêu cầu là Times New Roman.",
 "Arial/Tahoma/VNTime phổ biến nhưng không phải font chuẩn công văn theo đáp án đề. Thường kèm cỡ 13 hoặc 14 tùy quy định đơn vị."),
]

def main():
    src = json.loads(SRC.read_text(encoding="utf-8"))
    src_ids = [q["id"] for q in src["questions"]]
    assert len(RECORDS) == 120, len(RECORDS)
    assert [r[0] for r in RECORDS] == src_ids, "id mismatch"

    # Fresh file then write all
    lines = []
    for id_, icon, explain, detail in RECORDS:
        assert len(icon) >= 1 and explain.strip()
        obj = {"id": id_, "icon": icon, "explain": explain, "detail": detail}
        line = json.dumps(obj, ensure_ascii=False, separators=(",", ":"))
        assert "\n" not in line
        lines.append(line)

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")

    # Validate
    loaded = []
    with OUT.open(encoding="utf-8") as f:
        for i, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue
            obj = json.loads(line)
            assert set(obj) == {"id", "icon", "explain", "detail"}
            assert obj["explain"].strip()
            assert isinstance(obj["icon"], str) and len(obj["icon"]) >= 1
            loaded.append(obj["id"])

    assert len(loaded) == 120, len(loaded)
    assert loaded == src_ids
    print(f"OK: wrote {len(loaded)} lines to {OUT}")
    print(f"ids: {loaded[0]}..{loaded[-1]}")

if __name__ == "__main__":
    main()
